### ISSUE TITLE
Issue with p5.text

### ISSUE THREAD

**Issue by akaRicane** [davepagurek/p5.Framebuffer#17]
Hi dev team, 
I have been using this lib for a couple of weeks now, and I like it a lot. 

But for some reason, I cannot manage to draw some text on the canvas. I have tried a lot of options, like using a dedicated-to-texts frameBuffer inside mine, and nothing. The only message I happen to have  is: ```p5.js says: texture() was expecting p5.Image|p5.MediaElement|p5.Graphics for the first parameter, received object instead.``` . This message is just a friendly p5 message, and doesn't block anything. I precise, I use this lib in most of my sketches and I have no issues with it (except when I want to draw some text).

I import the lib in index.html (like all others) like: ``` <script type="text/javascript" src="core/externalLibs/p5/p5.Framebuffer.min.js"></script> ```

Worth mentioning:
> p5.js v1.4.0

I join a code sample down there. I have added an ellipse in the draw function to ensure P5 works.

## First case: I have nothing on screen (except the ellipse and the grey-ish background set as 100).

``` 
let textToShow = "FINALLY SOME TEXT";
let blockbold;
let TEXT_FB, F1_FB;

function preload() {
    blockbold = loadFont('assets/fonts/BlockBold.ttf');
}

function setup() {
    // creates canvas in WEBGL
    CNV = createCanvas(windowWidth, windowHeight, WEBGL);

    // build framebuffer objects
    F1_FB = createFramebuffer({ colorFormat: 'float' });
    TEXT_FB = createFramebuffer({ colorFormat: 'float' });
}

function draw() {
    background(0);
    F1_FB.draw(() => {
        clear();
        background(100);
        push();
        drawSomeTextHere();
        pop();
    });
    push()
    texture(F1_FB.color)
    plane(CNV.width, -CNV.height)
    pop()

    push()
    fill(360, 100, 100);
    ellipse(mouseX - CNV.width / 2, mouseY - CNV.height / 2, 50, 50);
    drawSomeTextHere();
    pop()
}

function drawSomeTextHere() {
    push();
    stroke(255);
    strokeWeight(10);
    textSize(30);
    textFont(blockbold);
    text(textToShow, 0, 0);
    pop();
}
``` 
## Second case, I have text on screen when I remove the script import in index.html.

```
let textToShow = "FINALLY SOME TEXT";
let blockbold;

function preload() {
    blockbold = loadFont('assets/fonts/BlockBold.ttf');
}

function setup() {
    // creates canvas in WEBGL
    CNV = createCanvas(windowWidth, windowHeight, WEBGL);
}

function draw() {
    background(0);
    push();
    fill(360, 100, 100);
    ellipse(mouseX - CNV.width / 2, mouseY - CNV.height / 2, 50, 50);
    drawSomeTextHere();
    pop();
}

function drawSomeTextHere() {
    push();
    stroke(255);
    strokeWeight(10);
    textSize(30);
    textFont(blockbold);
    text(textToShow, 0, 0);
    pop();
}
```

Thanks for your help 🙏

**Comment by davepagurek** [comment]
Thanks for the detailed test cases! I'm going to try debugging this. In the mean time, I generally handle text by drawing to a 2D canvas and then using that as a texture (or, for performance, caching the 2D canvas as a p5.Image using `the2DCanvas.get()`, since p5 can then be sure the content doesn't change every frame and doesn't need to waste time re-sending the data to the GPU every frame.) Maybe that can be a workaround?

I'll get back to you once I've taken a closer look figure out what the problem with WebGL text is!

**Comment by davepagurek** [comment]
Turns out the issue was setting `gl.UNPACK_FLIP_Y_WEBGL`. Not setting that doesn't affect having to flip the y axis when drawing the framebuffer to the screen, and it was breaking font rendering, so I'm just going to remove it. I've bumped the version on npm for 0.0.5, if you're using a CDN you can start using that version number to get code with the fix! I'll publish a new release on Github momentarily.

**Comment by akaRicane** [comment]
OMG it's works like a charm ! Can't believe it 🤩
Thanks so much
